[dependencies.clap]
features = ["derive"]
version = "4.5.32"

[dependencies.git]
path = "../git"

[dependencies.version]
path = "../version"

[package]
edition = "2024"
name = "cli"
version = "0.1.5"
