[dependencies.clap]
features = ["derive"]
version = "4.5.32"
[dependencies.git]
path = "../git"
[dependencies.version]
path = "../version"
[dependencies]
anyhow = "1.0"
colored = "2.0"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.8"
[package]
edition = "2024"
name = "cli"
version = "0.1.5"
