//! HTML templates with embedded CSS for self-contained reports

use crate::types::ComparisonResult;
use super::super::ReportMetadata;
use super::components::HtmlComponents;

/// HTML template generator for executive reports
pub struct HtmlTemplate;

impl HtmlTemplate {
    /// Create a new HTML template
    pub fn new() -> Self {
        Self
    }
    
    /// Render complete HTML report
    pub fn render(&self, results: &[ComparisonResult], metadata: &ReportMetadata, include_technical: bool) -> String {
        format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTTP Diff Executive Report - {}</title>
    <style>{}</style>
</head>
<body>
    <div class="container">
        <header class="report-header">
            <h1>🔍 HTTP Diff Executive Report</h1>
            <div class="report-subtitle">API Comparison Analysis</div>
        </header>
        
        {}
        
        {}
        
        {}
        
        {}
        
        <footer class="report-footer">
            <div class="footer-content">
                <div class="generated-info">
                    Generated by HTTP-Diff CLI • {} • {} environments tested
                </div>
                <div class="footer-note">
                    This report provides an executive summary of API endpoint comparisons across environments.
                </div>
            </div>
        </footer>
    </div>
</body>
</html>"#,
            metadata.timestamp.format("%Y-%m-%d"),
            Self::embedded_css(),
            HtmlComponents::executive_dashboard(results, metadata),
            HtmlComponents::results_table(results),
            HtmlComponents::recommendations(results),
            if include_technical { Self::technical_appendix(results) } else { String::new() },
            metadata.timestamp.format("%Y-%m-%d %H:%M %Z"),
            metadata.environments.len()
        )
    }
    
    /// Generate technical appendix with curl commands (if enabled)
    fn technical_appendix(results: &[ComparisonResult]) -> String {
        let mut curl_sections = String::new();
        
        for result in results.iter().filter(|r| r.has_errors || !r.is_identical) {
            curl_sections.push_str(&format!(r#"
            <div class="curl-section">
                <h4>📍 {} <span class="user-context">({})</span></h4>
                <div class="curl-commands">
            "#, 
                result.route_name,
                if result.user_context.is_empty() { 
                    "default".to_string() 
                } else { 
                    result.user_context.iter()
                        .map(|(k, v)| format!("{}={}", k, v))
                        .collect::<Vec<_>>()
                        .join(", ")
                }
            ));
            
            for (env_name, response) in &result.responses {
                let status_class = if response.is_error() { "error" } else { "success" };
                curl_sections.push_str(&format!(r#"
                <div class="curl-command">
                    <div class="env-header">
                        <span class="env-name">{}</span>
                        <span class="status-code {}">{}</span>
                    </div>
                    <div class="command-box">
                        <code>{}</code>
                        <button class="copy-btn" onclick="copyToClipboard(this)">📋</button>
                    </div>
                </div>
                "#, env_name.to_uppercase(), status_class, response.status, response.curl_command));
            }
            
            curl_sections.push_str("</div></div>");
        }
        
        if curl_sections.is_empty() {
            return String::new();
        }
        
        format!(r#"
        <div class="technical-appendix">
            <h2>🔧 Technical Reproduction Guide</h2>
            <div class="appendix-note">
                Use these curl commands to reproduce and debug issues locally.
            </div>
            {}
        </div>
        
        <script>
        function copyToClipboard(button) {{
            const code = button.previousElementSibling;
            navigator.clipboard.writeText(code.textContent).then(() => {{
                button.textContent = '✅';
                setTimeout(() => button.textContent = '📋', 2000);
            }});
        }}
        </script>
        "#, curl_sections)
    }
    
    /// Embedded CSS for self-contained reports
    fn embedded_css() -> &'static str {
        r#"
        /* Executive Report Styles */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f8f9fa;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: white;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
            border-radius: 8px;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        
        /* Header */
        .report-header {
            text-align: center;
            padding: 30px 0;
            border-bottom: 3px solid #e9ecef;
            margin-bottom: 30px;
        }
        
        .report-header h1 {
            font-size: 2.5em;
            color: #2c3e50;
            margin-bottom: 10px;
        }
        
        .report-subtitle {
            font-size: 1.2em;
            color: #6c757d;
            font-weight: 300;
        }
        
        /* Dashboard */
        .dashboard {
            margin-bottom: 40px;
        }
        
        .dashboard-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 25px;
        }
        
        .dashboard-header h2 {
            color: #2c3e50;
            font-size: 1.8em;
        }
        
        .timestamp {
            color: #6c757d;
            font-size: 0.95em;
        }
        
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 25px;
        }
        
        .metric-card {
            background: white;
            border: 2px solid #e9ecef;
            border-radius: 12px;
            padding: 25px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }
        
        .metric-card.primary {
            border-color: #007bff;
            background: linear-gradient(135deg, #007bff05 0%, #007bff10 100%);
        }
        
        .metric-card .metric-icon {
            font-size: 2em;
            margin-bottom: 15px;
        }
        
        .metric-value {
            font-size: 2.5em;
            font-weight: bold;
            margin-bottom: 5px;
        }
        
        .metric-value.success { color: #28a745; }
        .metric-value.warning { color: #ffc107; }
        .metric-value.error { color: #dc3545; }
        
        .metric-label {
            color: #6c757d;
            font-size: 1.1em;
            margin-bottom: 10px;
        }
        
        .progress-bar {
            background: #e9ecef;
            height: 8px;
            border-radius: 4px;
            overflow: hidden;
        }
        
        .progress-fill {
            height: 100%;
            border-radius: 4px;
            transition: width 0.5s ease;
        }
        
        .progress-fill.success { background: #28a745; }
        .progress-fill.warning { background: #ffc107; }
        .progress-fill.error { background: #dc3545; }
        
        .summary-stats {
            display: flex;
            justify-content: space-around;
            background: #f8f9fa;
            border-radius: 8px;
            padding: 20px;
        }
        
        .stat-item {
            text-align: center;
        }
        
        .stat-label {
            display: block;
            color: #6c757d;
            font-size: 0.9em;
            margin-bottom: 5px;
        }
        
        .stat-value {
            font-size: 1.3em;
            font-weight: bold;
            color: #2c3e50;
        }
        
        /* Results Table */
        .results-section {
            margin-bottom: 40px;
        }
        
        .results-section h2 {
            color: #2c3e50;
            margin-bottom: 20px;
            font-size: 1.8em;
        }
        
        .table-container {
            overflow-x: auto;
            border-radius: 8px;
            border: 1px solid #e9ecef;
        }
        
        .results-table {
            width: 100%;
            border-collapse: collapse;
            background: white;
        }
        
        .results-table th {
            background: #f8f9fa;
            color: #495057;
            font-weight: 600;
            padding: 15px 12px;
            text-align: left;
            border-bottom: 2px solid #e9ecef;
        }
        
        .results-table td {
            padding: 12px;
            border-bottom: 1px solid #e9ecef;
        }
        
        .results-table tr:hover {
            background: #f8f9fa;
        }
        
        .status-badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.85em;
            font-weight: 500;
        }
        
        .status-badge.success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }
        
        .status-badge.warning {
            background: #fff3cd;
            color: #856404;
            border: 1px solid #faeaa7;
        }
        
        .status-badge.error {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        
        .status-codes {
            font-family: monospace;
            font-size: 0.9em;
        }
        
        .status-code {
            display: inline-block;
            margin-right: 8px;
            padding: 2px 6px;
            border-radius: 3px;
            font-weight: 500;
        }
        
        .status-code.success {
            background: #d4edda;
            color: #155724;
        }
        
        .status-code.warning {
            background: #fff3cd;
            color: #856404;
        }
        
        .status-code.error {
            background: #f8d7da;
            color: #721c24;
        }
        
        /* Recommendations */
        .recommendations-section {
            margin-bottom: 40px;
        }
        
        .recommendations-section h2 {
            color: #2c3e50;
            margin-bottom: 20px;
            font-size: 1.8em;
        }
        
        .recommendation {
            display: flex;
            align-items: flex-start;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 15px;
            border-left: 4px solid;
        }
        
        .recommendation.success {
            background: #d4edda;
            border-left-color: #28a745;
        }
        
        .recommendation.warning {
            background: #fff3cd;
            border-left-color: #ffc107;
        }
        
        .recommendation.error {
            background: #f8d7da;
            border-left-color: #dc3545;
        }
        
        .recommendation.info {
            background: #d1ecf1;
            border-left-color: #17a2b8;
        }
        
        .recommendation-icon {
            font-size: 1.5em;
            margin-right: 15px;
            margin-top: 5px;
        }
        
        .recommendation-content strong {
            display: block;
            margin-bottom: 5px;
            font-size: 1.1em;
        }
        
        /* Technical Appendix */
        .technical-appendix {
            margin-top: 40px;
            padding-top: 30px;
            border-top: 2px solid #e9ecef;
        }
        
        .technical-appendix h2 {
            color: #2c3e50;
            margin-bottom: 15px;
            font-size: 1.8em;
        }
        
        .appendix-note {
            color: #6c757d;
            margin-bottom: 25px;
            font-style: italic;
        }
        
        .curl-section {
            margin-bottom: 30px;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            padding: 20px;
            background: #f8f9fa;
        }
        
        .curl-section h4 {
            color: #2c3e50;
            margin-bottom: 15px;
        }
        
        .user-context {
            font-weight: normal;
            color: #6c757d;
            font-size: 0.9em;
        }
        
        .curl-command {
            margin-bottom: 15px;
        }
        
        .env-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 8px;
        }
        
        .env-name {
            font-weight: bold;
            color: #495057;
        }
        
        .command-box {
            position: relative;
            background: #2c3e50;
            border-radius: 6px;
            padding: 15px;
        }
        
        .command-box code {
            color: #f8f9fa;
            font-family: 'Monaco', 'Menlo', monospace;
            font-size: 0.9em;
            line-height: 1.4;
            word-break: break-all;
            display: block;
            padding-right: 40px;
        }
        
        .copy-btn {
            position: absolute;
            top: 10px;
            right: 10px;
            background: #495057;
            border: none;
            color: white;
            padding: 5px 8px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 0.8em;
        }
        
        .copy-btn:hover {
            background: #6c757d;
        }
        
        /* Footer */
        .report-footer {
            margin-top: 50px;
            padding-top: 30px;
            border-top: 2px solid #e9ecef;
            text-align: center;
            color: #6c757d;
        }
        
        .generated-info {
            font-weight: 500;
            margin-bottom: 5px;
        }
        
        .footer-note {
            font-size: 0.9em;
            font-style: italic;
        }
        
        /* Print Styles */
        @media print {
            body { background: white; }
            .container { 
                box-shadow: none; 
                margin: 0;
                border-radius: 0;
            }
            .copy-btn { display: none; }
            .technical-appendix { page-break-before: always; }
        }
        
        /* Mobile Responsive */
        @media (max-width: 768px) {
            .container { margin: 10px; padding: 15px; }
            .metrics-grid { grid-template-columns: 1fr; }
            .summary-stats { flex-direction: column; gap: 15px; }
            .dashboard-header { flex-direction: column; text-align: center; }
            .results-table { font-size: 0.9em; }
            .results-table th, .results-table td { padding: 8px 6px; }
        }
        "#
    }
}

impl Default for HtmlTemplate {
    fn default() -> Self {
        Self::new()
    }
}