name: Build and Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: fnc

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openssl@3
          if [ "${{ matrix.target }}" = "x86_64-apple-darwin" ]; then
            # For x86_64, we need to specify the Intel path
            echo "OPENSSL_DIR=$(brew --prefix)/Cellar/openssl@3/3.4.1" >> $GITHUB_ENV
            # Make sure we use the x86_64 version
            brew fetch --bottle-tag=x86_64_monterey openssl@3
            mkdir -p /tmp/openssl-x86
            tar -xf $(find . -name 'openssl@3-*.mojave.bottle*.tar.gz' -o -name 'openssl@3-*.catalina.bottle*.tar.gz' -o -name 'openssl@3-*.monterey.bottle*.tar.gz' -o -name 'openssl@3-*.x86_64_*.bottle*.tar.gz' | head -n 1) -C /tmp/openssl-x86
            echo "OPENSSL_LIB_DIR=/tmp/openssl-x86/opt/openssl@3/lib" >> $GITHUB_ENV
            echo "OPENSSL_INCLUDE_DIR=/tmp/openssl-x86/opt/openssl@3/include" >> $GITHUB_ENV
          else
            # For arm64, use default Homebrew path
            echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          fi
          # For cross-compilation
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      - name: Build Binary
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}

      - name: Package Binary
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/${PROJECT_NAME} release/
          cd release
          tar -czf ../fnc-${{ matrix.name }}.tar.gz *
          cd ..
          echo "ASSET_PATH=fnc-${{ matrix.name }}.tar.gz" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}