name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: cross build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/fnc release/
          cd release
          tar -czf ../fnc-${{ matrix.target }}.tar.gz *
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fnc-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
