name: Build and Release
on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: fnc

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: macos-intel
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-apple-silicon
            runner: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}

      - name: Package Binary
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/${PROJECT_NAME} release/
          cd release
          tar -czf ../${PROJECT_NAME}-${{ matrix.name }}.tar.gz *
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${PROJECT_NAME}-${{ matrix.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
