name: Build and Release
on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
  PROJECT_NAME: fnc # Assuming 'fnc' is your project name

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Install OpenSSL (macOS)
        run: |
          brew install openssl@3
          echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.bash_profile
          export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
          export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"

      - name: Build Binary
        run: cargo build --verbose --locked --release --target ${{ matrix.target }}
        env:
          OPENSSL_DIR: /usr/local/opt/openssl@3

      - name: Package Binary
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/${PROJECT_NAME} release/
          cd release
          tar -czf ../${PROJECT_NAME}-${{ matrix.name }}.tar.gz *
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${PROJECT_NAME}-${{ matrix.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
